name: test workflow
permissions: write-all
on:
  workflow_dispatch:

jobs:
  call-terraform-plan:
    permissions: write-all
    uses: Pavan-Balaji22/Github-Actions-Workflows/.github/workflows/hello-world.yaml@master
